#!/usr/bin/env zsh

local cmd=${1:-run} supported_cmd=( show run cp rm )

if (( $supported_cmd[(I)$cmd] )); then
  if [[ -n $1 ]]; then
    shift
  fi

  local model=($(
    ollama list |
    sort |
    fzf --prompt="❯ ollama $cmd " --header-lines=1 $( [[ $cmd == rm ]] && printf --multi ) |
    cut -f1
  ))

  if [[ -n $model ]]; then
    print "ollama $cmd $model $@"
    ollama $cmd $model $@
  fi
else
  print "Unsupported command. $0:t only accepts the following:\n $supported_cmd" >&2
  return 1
fi
