#!/usr/bin/env zsh

typeset -A archs=( [x86_64]=arm64 [arm64]=x86_64 )
arch=( `lipo -archs $1` )
dylib=$1:t

if [[ -n $archs[$arch] ]]; then
  url=http://buildbot.libretro.com/nightly/apple/osx/$archs[$arch]/latest/$dylib.zip
  if curl -o /dev/null --silent --head --fail $url; then
    tmpdir=`mktemp -d`
    curl -Lo $tmpdir/$dylib.zip $url
    unzip $tmpdir/$dylib.zip -d $tmpdir

    if lipo -create $1 $tmpdir/$dylib -output $tmpdir/universal-$dylib; then
      mv -f $tmpdir/universal-$dylib $1
    fi
    rm -rf $tmpdir
  fi
fi
