#!/usr/bin/env zsh

typeset -A arch_flip=( [x86_64]=arm64 [arm64]=x86_64 )
arch=( `lipo -archs $1` )
dylib=$1:t

if [[ -n $arch_flip[$arch] ]]; then
  url=http://buildbot.libretro.com/nightly/apple/osx/$arch_flip[$arch]/latest/$dylib.zip
  if curl -o /dev/null --silent --head --fail $url; then
    sleep 2
    tmpdir=`mktemp -d`
    if curl -Lo $tmpdir/$dylib.zip $url; then
      unzip $tmpdir/$dylib.zip -d $tmpdir 
      if lipo -create $1 $tmpdir/$dylib -output $tmpdir/universal-$dylib; then
        mv -vf $tmpdir/universal-$dylib $1
      fi
    fi
    rm -rf $tmpdir
  fi
fi
