#!/usr/bin/env zsh

zparseopts -D -E - {h,-help}=help {x,-x86}=x86 -metal-hud=metal_hud

# Call directly for help since `open` does not stream to stdout.
if [[ -n $help ]]; then
  if app_dir=`mdfind kMDItemCFBundleIdentifier = com.libretro.dist.RetroArch | head -n 1`; then
    $app_dir/Contents/MacOS/RetroArch $help
  fi
  exit
fi

if [[ -n $args ]]; then
  args=( --args $args )
fi

if [[ -n $x86 ]]; then
  args=( --arch x86_64 $args )
fi

if [[ -n $metal_hud ]]; then
  args=(
    --env MTL_HUD_ENABLED=1
    --env MTL_HUD_CONFIG_FILE=$HOME/.config/metal-hud/default.plist
    $args
  )
fi

open -b com.libretro.dist.RetroArch $args
