#!/usr/bin/env zsh

_brew_check tag libxmlb || return 1

local int tag_valid
zparseopts -D -E -F - {t,-tag-valid}=tag_valid || return 1
trap 'int=1' INT TERM

while read i; do
	ok=() nf=() h=`unzip -p $i | md5`
	printf "%s\n" $i
	for db in ~/Games/Support/xmlb/*.xmlb; do
		if xb-tool query $db "datafile/game/rom[@md5='$h']" | sed 's/^RESULT: //1' | xpath -q -e "string(rom/@name)" &> /dev/null
		then
			ok+=( $db:t:r )
			break
		else
			nf+=( $db:t:r )
		fi
	done
	test $int && break

	if [[ -n $ok ]]; then
		printf "\033[0;36m ok: %s \033[0m\n" $ok
		if [[ $tag_valid ]]; then
			for db in $ok; tag -a "Validated:$db" "$i:a"
		fi
	elif [[ -n $nf ]]; then
		printf "\033[0;31m nf: %s \033[0m\n" $nf
	fi
done < <( find ${@:-.} -name "*.zip" )
