#!/usr/bin/env zsh
#function brew-bundle {
  local name set changesFrom
  zparseopts -D -E - {n,-name}:=name {-all,-formula,-brews,-cask,-casks,-tap,-taps,-vscode}=set {c,-changes-from}:=changesFrom || return 1
  if [[ -z $name && -z $set ]]
  then
    name=default 
    set=(--formula --cask) 
  elif [[ -z $name && ${#set[@]} == 1 ]]
  then
    name=${set/--/} 
  elif [[ -n $name ]]
  then
    name=${name[-1]} 
  else
    print -- "--name <name> required for multiple listed: $set." >&2
    return 1
  fi
  if [[ -n $changesFrom ]]
  then
    local base temp bundle
    base=~/.config/brew/bundle-$changesFrom[-1]-`machine` 
    if [[ -f $base ]]
    then
      temp=`mktemp` 
      brew bundle $@ $set --describe --no-lock --force --file $temp
      bundle=~/.config/brew/bundle-$name-changesFrom-`machine` 
      print "# changesFrom from 'bundle-$changesFrom[-1]-`machine`':" > $bundle
      while read l
      do
        if ! grep -Fq $l $base
        then
          print -- $l
        fi
      done < <( cat $temp ) >> $bundle
      rm $temp
    else
      print "Base file for changes not found." >&2
      return 1
    fi
  else
    brew bundle $@ $set --describe --no-lock --file ~/.config/brew/bundle-$name-`machine`
  fi
#}
