#!/usr/bin/env zsh

zparseopts -D -E -F - {t:,-tool:}=tool || return 1

if [[ -n $tool ]]; then
  _tool=${tool[-1]}
  unset tool
elif [[ -z $_tool ]]; then
  _tool=(diff -u)
fi

if [[ -z $_defaults_before ]]; then
  _defaults_before=`mktemp`
  _domain=$1
  if [[ -z $_domain ]]; then
    print "Warning! Domain was not set. All preferences will be monitored for changes."
  fi
  defaults read $_domain > $_defaults_before
  if [[ $? == 0 ]]; then
    print "Ready for changes in ${_domain:-all domains}."
  else
    rm $_defaults_before
    unset _tool _domain _defaults_before
  fi
else
  _defaults_after=`mktemp`
  defaults read $_domain > $_defaults_after
  $_tool $_defaults_before $_defaults_after
  rm $_defaults_before $_defaults_after
  unset _tool _domain _defaults_before _defaults_after
fi
