#!/usr/bin/env zsh

local remove_archive archive
zparseopts -D -E -F - {r,-remove}=remove_archive || return 1

for archive in "$@"; do
  if [[ -f $archive ]]; then
    case $archive in
      *.7z)       7z x $archive        ;; # require p7zip
      *.bz2)      bunzip2 $archive     ;;
      *.gz)       gunzip $archive      ;;
      *.iso)      7z x $archive        ;; # require p7zip
      *.rar)      7z x $archive        ;; # require p7zip
      *.tar.bz2)  tar xjf $archive     ;;
      *.tar.gz)   tar xzf $archive     ;;
      *.tar)      tar xf $archive      ;;
      *.tbz2)     tar xjf $archive     ;;
      *.tgz)      tar xzf $archive     ;;
      *.Z)        uncompress $archive  ;;
      *.zip)      unzip $archive       ;;
      *)          echo "'$archive' cannot be extracted." ;;
    esac
    if [[ $? == 0 && $remove_archive ]]; then
      rm $archive
      echo "'$archive' removed."
    fi
  else
    echo "'$archive' is not a valid archive."
	fi
done
