#!/usr/bin/env zsh

local trash archive
zparseopts -D -E -F - {t,-trash-archive}=trash || return 1

for archive in "$@"; do
  if [[ -f $archive ]]; then
    case $archive in
      *.(7z|iso|rar)) ! _brew_check p7zip ||
              7z x $archive       ;;
      *.bz2)  bunzip2 $archive    ;;
      *.gz)   gunzip $archive     ;;
      *.tar)  tar xf $archive     ;;
      *.(tbz|tbz2|tar.bz2))
              tar xjf $archive    ;;
      *.(tgz|tar.gz))
              tar xzf $archive    ;;
      *.Z)    uncompress $archive ;;
      *.zip)  unzip $archive      ;;
      *)      echo "'$archive' cannot be extracted." ;;
    esac
    if [[ $? == 0 && $trash ]]; then
      trash $archive
      echo "'$archive' moved to trash."
    fi
  else
    echo "'$archive' is not a valid archive."
	fi
done
