#!/usr/bin/env zsh
# https://github.com/mattmc3/zephyr/tree/main/plugins/zfunctions
#function function-refresh {
  if (( $# == 0 ))
  then
    echo "$0: Expecting function argument." >&2
    return 1
  elif ! (( $+functions[$1] ))
  then
    echo "$0: Function not found '$1'." >&2
    return 1
  fi
  unfunction $1
  autoload -Uz $1
#}
