#!/usr/bin/env zsh

local rompath=`pwd`
# first parameter can be ambigous. assume directory if it exists.
if [[ -n $1 && ${1[1]} != - ]]; then
  if [[ -d ${1:a} ]]; then
    rompath=${1:a}
    shift
  else
    print "Using '$1' as a search query."
  fi
fi
lmame $@ -rompath $rompath
