#!/usr/bin/env zsh

local model=`while read l; do
  printf "%s:%s\n" $l:h:t $l:t
done < <( find ~/.ollama/models/manifests/registry.ollama.ai -type f ) | sort | fzf`

if [[ -n $model ]]; then
  print -- "ollama $@ $model"
  ollama $@ $model
fi
