#!/usr/bin/env zsh
#function mamexml-to-json {
  if [[ ! -t 0 ]]
  then
    input=/dev/stdin
  else
    input=$1
    shift
  fi
  cat $input | oq -i xml -o json '
  {
    version:.mame."@build" | match("^[0-9.]+").string,
    machine:[ .mame.machine | if type == "array" then . else [.] end | .[] | {
      name:."@name",
      description:.description,
      manufacturer:.manufacturer,
      year:.year,
      source:."@sourcefile",
      runnable:."@runnable",
      isbios:."@isbios",
      isdevice:."@isdevice",
      cloneof:."@cloneof",
      romof:."@romof",
      sampleof:."@sampleof",
      driver:.driver,
      display:.display,
      sound:.sound,
      input:.input,
      biosset:.biosset,
      rom:.rom,
      disk:.disk,
      sample:.sample,
      device:.device,
      device_ref:.device_ref
    }]
  } | walk(
    if type == "object" then with_entries(select(.value != null) | .key |= ltrimstr("@")) else . end
  )' > $1
#}
