#!/usr/bin/env zsh
# read man page with Preview.app
#function manp {
  if ! (( $# ))
  then
    echo 'manp: You must specify the manual page you want' >&2
    return 1
  fi
  mandoc -T pdf "$(/usr/bin/man -w $@)" | open -fa Preview
#}
