#!/usr/bin/env zsh
#function metal-hud {
case $1 in
	(enable) launchctl setenv MTL_HUD_ENABLED 1 ;;
	(disable) launchctl unsetenv MTL_HUD_ENABLED ;;
	(toggle)
		if [[ `launchctl getenv MTL_HUD_ENABLED` == 1 ]]
		then
			launchctl unsetenv MTL_HUD_ENABLED
		else
			launchctl setenv MTL_HUD_ENABLED 1
		fi ;;
esac

if [[ `launchctl getenv MTL_HUD_ENABLED` == 1 ]]
then
	launchctl setenv MTL_HUD_CONFIG_FILE $HOME/.config/metal-hud.plist
	print enabled
else
	launchctl unsetenv MTL_HUD_CONFIG_FILE
	print disabled
fi
#}
