#!/usr/bin/env zsh
#function metal-hud {
case $1 in
	(enable) launchctl setenv MTL_HUD_ENABLED 1 ;;
	(disable) launchctl unsetenv MTL_HUD_ENABLED ;;
	(toggle)
		if [[ `launchctl getenv MTL_HUD_ENABLED` == 1 ]]
		then
			launchctl unsetenv MTL_HUD_ENABLED
		else
			launchctl setenv MTL_HUD_ENABLED 1
		fi ;;
esac

if [[ `launchctl getenv MTL_HUD_ENABLED` == 1 ]]
then
	launchctl setenv MTL_HUD_OPACITY 0.75
	launchctl setenv MTL_HUD_SCALE 0.15
	print enabled
else
	launchctl unsetenv MTL_HUD_OPACITY
	launchctl unsetenv MTL_HUD_SCALE
	print disabled
fi
#}
