#!/usr/bin/env zsh

#function retroarch-build {
  local zall zforce zupdate
  zparseopts -D -F - -all=zall -force=zforce -update=zupdate || return 1

  local configs=( Release Debug )
  if [[ -n ${@:|configs} ]]; then
    print "Unknown build configuration: ${@:|configs}" >&2
    return 1
  fi
  local builds=( ${@:-Release} )
  if (( ${#zall} )); then
    builds=( $configs )
  fi
  print "Building for the following: ${(j:, :)builds}"

  local base_dir=~/Projects/emulation/libretro
  local repos=(
    retroarch-apple-deps
    libretro-super/retroarch
  )
  local cdi=0
  local updates=0
  local stashed=()

  if (( ${#zupdate} )); then
    for repo in $repos; do
      if ! () {
        cd $base_dir/$repo || return 1
        let cdi++
        print "Updating repo: $repo"
      }; then
        return 1
      elif ! git fetch; then
        print "fetch failed." >&2
        return 1
      elif (( $( git rev-list --count HEAD..@{u} ) > 0 )); then
        let updates++
        if git stash | grep -q '^Saved working directory'; then
          stashed+=$repo
        fi
        if ! git pull; then
          print "pull failed." >&2
          return 1
        fi
        if [[ -n $( git submodule status ) ]] &&
          ! git submodule update --init --recursive
        then
          print "submodule update failed." >&2
          return 1
        fi
      fi
    done
  fi

  if (( updates > 0 || ${#zforce} )); then
    # stash for self-signing required for local build.
    if ! git stash apply refs/`git stash list | sed -En 's/^(.+):.+: self-sign$/\1/p'`; then
      print "stash apply ::self-sign:: failed" >&2
      return 1
    fi
  else
    print "Nothing to update."
    cd +${cdi}
    return 0
  fi

  local config project=pkg/apple/RetroArch_Metal.xcodeproj
  if [[ ! -d $project ]]; then
    print "Project doesn't exist: $project" >&2
    return 1
  fi
  xcodebuild clean -project $project
  for config in $builds; do
    if ! xcodebuild -target RetroArch -configuration $config -project $project; then
      print "xcode build failed for '-configuration $config'." >&2
      return 1
    fi
  done

  print "Builds completed for the following: ${(j:, :)builds}."
  print "Restoring repo states:"
  # reset self-signing stash.
  git reset --hard HEAD
  # restore previously stashed.
  for repo in $stashed; [[ $PWD != $base_dir/$repo ]] && {
    cd $base_dir/$repo
    let cdi++
    if ! git stash pop; then
      return 1
    fi
  }
  # restore working directory.
  cd +${cdi}

#}
