#!/usr/bin/env zsh

local int basepath=`pwd`
trap 'int=1' INT TERM

while read -r p; do
	printf "\n\e[1;30m%s\e[0m\n" $p
	cd "$basepath/$p"
	git $@
	test $int && break
done < <( rgit-paths )

cd "$basepath"
