#!/usr/bin/env zsh
#function rgit {
  local int basepath=`pwd` 
  trap 'int=1' INT TERM
  while read -r p
  do
    printf "\n\e[1;15m%s\e[0m\n" $p
    cd "$basepath/$p"
    git $@
    test $int && break
  done < <( rgit-paths )
  cd "$basepath"
#}
