#!/usr/bin/env zsh
#function rominfo-generate {
  if type mame &>/dev/null; then
    # Remove decimals and truncate. MAME version 0.250.0.1 results in 0250.
    local version=`mame -version | awk -F'[ .]' '{print $1$2}'`
  else
    return 1
  fi
  local base=${1:-.}
  local infodir=$base/.rominfo/$version

  if [[ -d $infodir && $infodir -nt $base ]]; then
    return
  fi

  mkdir -p $infodir
  ln -sF $version $base/.rominfo/info

  echo "Generating .rominfo/$version..."
  for rom in $base/*.zip
  do
    rominfo=$infodir/$rom:t:r.json
    if [[ ! -f $rominfo ]]
    then
      mame -listxml $rom:t:r | mamexml-to-json $rominfo
    fi
  done

  touch $infodir
#}
