#!/usr/bin/env zsh
#function rtag-github {
  if _brew_check tag
  then
    while read -r p
    do
      printf "\e[1;30m%s\e[0m\n" $p
      tag -a "GitHub Repo" "$p"
    done < <( rgit-paths )
  fi
#}
