#!/usr/bin/env zsh
#function update-ollama-models {
  local models list
  models=`ollama ls | awk '(NR > 1) {print $1}'` 
  list=(${(f)models}) 
  for m in ${(i)list}
  do
    print -- "Updating $m."
    ollama pull $m
    sleep 1
done
#}
