#!/usr/bin/env zsh
case $1 in
	(enable)	launchctl setenv MTL_HUD_ENABLED 1 ;;
	(disable) launchctl unsetenv MTL_HUD_ENABLED ;;
	(toggle)
		if [[ `launchctl getenv MTL_HUD_ENABLED` == 1 ]]; then
			launchctl unsetenv MTL_HUD_ENABLED
		else
			launchctl setenv MTL_HUD_ENABLED 1
		fi
	;;
esac

if [[ `launchctl getenv MTL_HUD_ENABLED` == 1 ]]; then
	echo enabled
else
	echo disabled
fi
