name: local
version: v1
schema: v1
models:
  - name: qwen2.5-coder.1.5b-mlx
    provider: ollama
    model: oamazonasgabriel/qwen2.5-coder.1.5b-mlx:f16-8gbGPU
    roles:
      - autocomplete

  - name: codegemma:2b-code
    provider: ollama
    model: codegemma:2b-code
    roles:
      - autocomplete

  - name: qwen2.5-coder:1.5b-base
    provider: ollama
    model: qwen2.5-coder:1.5b-base
    roles:
      - autocomplete

  - name: qwen3-embedding
    provider: ollama
    model: qwen3-embedding:0.6b
    roles:
      - embed

  - name: nomic-embed-text
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed

  - name: Ollama Autodetect
    provider: ollama
    model: AUTODETECT
