name: local
version: v1
schema: v1
models:
  - name: gemma4:26b-mlx
    provider: ollama
    model: gemma4:26b-mlx
    roles:
      - chat
      - edit

  - name: gemma4:31b-cloud
    provider: ollama
    model: gemma4:31b-cloud
    roles:
      - chat
      - edit

  - name: qwen3.8:27b-mlx
    provider: ollama
    model: qwen3.8:27b-mlx
    roles:
      - chat
      - edit

  - name: qwen3.8:27b-mlx-apply
    provider: ollama
    model: qwen3.8:27b-mlx
    promptTemplates:
      apply: |
        Original: {{{original_code}}}
        New: {{{new_code}}}

        Please generate the final code without any markers or explanations.
    roles:
      - apply

  - name: qwen2.5-coder:1.5b
    provider: ollama
    model: qwen2.5-coder:1.5b-base-q8_0
    roles:
      - autocomplete

  - name: embeddinggemma
    provider: ollama
    model: embeddinggemma-2:270m-mxfp8-text
    roles:
      - embed
